version: '3'
services:
  frontend:
    build: ./client
    image: "reactapp:1.0.0"
    restart: unless-stopped
    networks:
      - sub-etha
  backend:
    build: ./server
    image: "expressapp:1.0.0"
    restart: unless-stopped
    networks:
      - sub-etha
    depends_on:
      - db
    environment: 
      TZ: Asia/Taipei
  revproxy:
    build: ./nginx
    image: "reverseproxy:1.0.0"
    restart: unless-stopped
    networks:
      - sub-etha
    ports:
      - 80:80
    links:
      - db
    depends_on: 
      - frontend
      - backend
      - flask
  flask:
    build: ./flask
    image: "flaskapp:1.0.0"
    restart: unless-stopped
    networks:
      - sub-etha
  db:
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Taipei
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - sub-etha
networks:
  sub-etha:
    driver: bridge
volumes:
  dbdata:
    driver: local
